services:
  - type: web
    name: pto-connect-backend
    runtime: node
    plan: free # or 'starter', 'standard' depending on your tier
    branch: main
    buildCommand: ./render-build.sh
    startCommand: node index.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_MONTHLY_PRICE_ID
        sync: false
      - key: STRIPE_ANNUAL_PRICE_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
