services:
  - type: web
    name: pto-connect-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER_DISABLE_CACHE
        value: "true"
      - key: NPM_CONFIG_PACKAGE_LOCK
        value: "true"
