services:
  - type: web
    name: pto-connect-backend
    env: node
    plan: free
    buildCommand: |
      echo "Clearing any existing files..."
      rm -rf node_modules .pnpm-store pnpm-lock.yaml package-lock.json || true
      find . -name "node_modules" -type d -exec rm -rf {} + 2>/dev/null || true
      find . -name ".pnpm" -type d -exec rm -rf {} + 2>/dev/null || true
      echo "Installing with npm..."
      npm cache clean --force || true
      npm install --no-package-lock --prefer-offline=false
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PACKAGE_LOCK
        value: "false"
      - key: NPM_CONFIG_PREFER_OFFLINE
        value: "false"
