services:
  - type: web
    name: pto-connect-backend
    env: node
    plan: free
    buildCommand: rm -rf node_modules package-lock.json pnpm-lock.yaml && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PACKAGE_LOCK
        value: "true"
