name: Deploy to Railway

on:
  push:
    branches: [ main ]
    paths: [ 'pto-connect-backend/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'pto-connect-backend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: pto-connect-backend/package-lock.json
        
    - name: Install dependencies
      working-directory: ./pto-connect-backend
      run: npm ci
      
    - name: Run tests (if any)
      working-directory: ./pto-connect-backend
      run: npm test --if-present
      
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Deploy to Railway
      working-directory: ./pto-connect-backend
      run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
